# Generated by Django 4.2.7 on 2023-12-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='maker',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='price',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
