# Generated by Django 4.2.7 on 2023-12-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_person_maker_person_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='maker',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='price',
            field=models.CharField(default='', max_length=10),
        ),
    ]
