# Generated by Django 4.2.7 on 2023-12-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_person_category_alter_person_age_alter_person_maker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='price',
            field=models.TextField(default='', max_length=10),
        ),
    ]
