# Generated by Django 4.2.7 on 2023-12-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_person_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.TextField(default=''),
        ),
    ]
