# Generated by Django 4.2.7 on 2023-12-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_alter_person_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.TextField(),
        ),
    ]
