# Generated by Django 4.2.7 on 2023-12-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_alter_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='price',
            field=models.IntegerField(default='', max_length=10),
        ),
    ]
