# Generated by Django 4.2.7 on 2023-12-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_alter_person_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='price',
            field=models.FloatField(default='', max_length=10),
        ),
    ]
